"""Bundles src/*.lua (in load order) into DungeonAutofarm.lua, one loadstring-able file.

    python tools/build.py

Runs tools/check.py first and refuses to build if it fails, so the bundle can never
contain a module that does not parse or references a name no module exports.

Each module keeps its own function scope in the bundle, so Luau's 200-register
cap applies per module, not to the whole file - the reason the split was done.
"""
import os
import re
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from modules import ROOT, SRC, BUNDLE, ORDER  # noqa: E402


def read_version(core_src):
    def grab(key):
        m = re.search(r'^local %s = "([^"]*)"' % key, core_src, re.M)
        return m.group(1) if m else "?"
    return grab("SCRIPT_VERSION"), grab("SCRIPT_CODENAME"), grab("SCRIPT_BUILD_DATE")


def main():
    check = subprocess.run([sys.executable, os.path.join(ROOT, "tools", "check.py")])
    if check.returncode != 0:
        print("build aborted: check.py failed")
        return 1

    parts = []
    core = open(os.path.join(SRC, "core.lua"), encoding="utf-8").read()
    version, codename, date = read_version(core)
    parts.append(
        "-- DungeonAutofarm.lua - BUILT FILE, DO NOT EDIT. Generated by tools/build.py from src/*.lua.\n"
        "-- Edit the module in src/, then run `python tools/build.py` to regenerate this bundle.\n"
        f"-- Version {version} \"{codename}\", build {date}.\n"
        "--\n"
        "-- Each module below is a function receiving the shared table S; modules run in load\n"
        "-- order and each one lives in its own function scope (Luau caps a scope at 200 registers).\n"
        "local S = {}\n"
    )
    for name in ORDER:
        src = open(os.path.join(SRC, f"{name}.lua"), encoding="utf-8").read().rstrip("\n")
        parts.append(
            f"\n-- ===================================== src/{name}.lua =====================================\n"
            "do\n"
            "    local module = (function()\n"
            f"{src}\n"
            "    end)()\n"
            "    module(S)\n"
            "end\n"
        )
    bundle = "".join(parts)
    open(BUNDLE, "w", encoding="utf-8", newline="\n").write(bundle)
    print(f"wrote {os.path.relpath(BUNDLE, ROOT)}: {bundle.count(chr(10))} lines, v{version} \"{codename}\"")

    # Belt and braces: the bundle itself must parse too.
    from luatools import lua_parse_error
    err = lua_parse_error(bundle, "DungeonAutofarm")
    if err:
        print("BUNDLE DOES NOT PARSE:", err)
        return 1
    print("bundle parses OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
